---
name: Main
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_API_TOKEN }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop
      - name: Test
        run: bundle exec rspec
